import{afterAll,beforeAll,describe,expect,it}from"vitest";
import{Pool,type PoolClient}from"pg";
import{creditGrossEarning}from"@/lib/server/earning-split-service";
import{enqueueAutomaticWithdrawal}from"@/lib/server/withdrawal-service";

const url=process.env.FINANCIAL_TEST_DATABASE_URL;
const integration=url?describe:describe.skip;
integration("Financial corrections PostgreSQL integration",()=>{
 const pool=new Pool({connectionString:url,ssl:false});let client:PoolClient;const oldEnabled=process.env.AUTO_WITHDRAW_ENABLED;
 beforeAll(async()=>{client=await pool.connect();expect((await client.query("SELECT 1 FROM schema_migrations WHERE filename='016_dividend_package_income_attribution.sql'")).rowCount).toBe(1)});
 afterAll(async()=>{if(oldEnabled===undefined)delete process.env.AUTO_WITHDRAW_ENABLED;else process.env.AUTO_WITHDRAW_ENABLED=oldEnabled;client.release();await pool.end()});
 async function user(marker:number){const wallet=`0x${marker.toString(16).padStart(40,"0")}`,row=(await client.query<{id:string}>("INSERT INTO users(wallet_address,status) VALUES($1,'ACTIVE') RETURNING id",[wallet])).rows[0];await client.query(`INSERT INTO user_package_states(user_id,registration_value,total_eligible_value,total_earning_cap,remaining_cap) VALUES($1,2000000,200000000,1000000000,1000000000)`,[row.id]);return row.id}
 it("caps and splits every migrated category exactly once with deterministic remainder",async()=>{await client.query("BEGIN");process.env.AUTO_WITHDRAW_ENABLED="false";try{const id=await user(Date.now());const types=["DIRECT_INCOME","MAGIC_LEVEL_INCOME","X3_PACKAGE","X3_HOLD_RELEASE","X4_GLOBAL","BOOSTER","GLOBAL_AUTOPOOL","DAILY_DIVIDEND"];for(const[type,index]of types.map((x,i)=>[x,i]as const)){const input={userId:id,incomeType:type,sourceReference:`financial-it:${index}`,grossAmount:101n,idempotencyKey:`financial-it:${id}:${index}`},first=await creditGrossEarning(input,client),retry=await creditGrossEarning(input,client);expect(first).toMatchObject({credited:101n,magic:10n,income:91n,duplicate:false});expect(retry.duplicate).toBe(true)}const counts=(await client.query<{caps:string;splits:string;magic:string;income:string}>(`SELECT (SELECT count(*)::text FROM income_credit_ledger WHERE user_id=$1) caps,(SELECT count(*)::text FROM earning_split_events WHERE user_id=$1) splits,(SELECT count(*)::text FROM magic_funding_events WHERE user_id=$1) magic,(SELECT count(*)::text FROM income_wallet_ledger WHERE user_id=$1 AND direction='CREDIT') income`,[id])).rows[0];expect(counts).toEqual({caps:"8",splits:"8",magic:"8",income:"8"})}finally{await client.query("ROLLBACK")}},30_000);
 it("reserves only the full eligible Income Wallet balance at the $1 threshold",async()=>{await client.query("BEGIN");process.env.AUTO_WITHDRAW_ENABLED="true";try{const below=await user(Date.now()+1),exact=await user(Date.now()+2),large=await user(Date.now()+3);for(const[id,amount]of[[below,999_999n],[exact,1_000_000n],[large,9_000_000n]]as const)await client.query(`INSERT INTO income_wallet_ledger(user_id,direction,amount,reason,idempotency_key) VALUES($1,'CREDIT',$2,'EARNING_NET',$3)`,[id,amount.toString(),`financial-withdraw:${id}`]);expect(await enqueueAutomaticWithdrawal(client,below)).toBeNull();const exactId=await enqueueAutomaticWithdrawal(client,exact),largeId=await enqueueAutomaticWithdrawal(client,large);expect(exactId).toBeTruthy();expect(await enqueueAutomaticWithdrawal(client,exact)).toBeNull();expect((await client.query("SELECT gross_reserved::text,fee_amount::text,net_payout::text FROM auto_withdrawals WHERE id=$1",[exactId])).rows[0]).toEqual({gross_reserved:"1000000",fee_amount:"100000",net_payout:"900000"});expect((await client.query("SELECT gross_reserved::text,fee_amount::text,net_payout::text FROM auto_withdrawals WHERE id=$1",[largeId])).rows[0]).toEqual({gross_reserved:"9000000",fee_amount:"900000",net_payout:"8100000"})}finally{await client.query("ROLLBACK")}},30_000);
});
