import{afterAll,beforeAll,describe,expect,it}from"vitest";import{Pool}from"pg";import{pauseModule,resumeModule,isModulePaused}from"@/lib/server/module-control-service";import{recordHeartbeat,refreshWorkerAlerts,upsertAlert,runDatabaseReconciliation}from"@/lib/server/operations-service";
const url=process.env.OPERATIONS_TEST_DATABASE_URL,integration=url?describe:describe.skip;
integration("Operations PostgreSQL integration",()=>{const pool=new Pool({connectionString:url,ssl:false});let wallet="";
 beforeAll(async()=>{process.env.DATABASE_URL=url;expect((await pool.query("SELECT 1 FROM schema_migrations WHERE filename='017_operations_control.sql'")).rowCount).toBe(1);wallet=`0x${Date.now().toString(16).padStart(40,"0").slice(-40)}`;await pool.query("INSERT INTO users(wallet_address,status,role) VALUES($1,'ACTIVE','ADMIN')",[wallet])});
 afterAll(async()=>{if(await isModulePaused("AUTO_WITHDRAW_WORKER"))await resumeModule("AUTO_WITHDRAW_WORKER",wallet,"test cleanup","RESUME_AUTO_WITHDRAW",`operations:test:cleanup:${Date.now()}`);await pool.query("UPDATE worker_heartbeats SET current_status='STOPPED',last_heartbeat_at=now(),updated_at=now() WHERE worker_name='integration-worker'");await pool.query(`UPDATE operations_alerts SET status='RESOLVED',resolved_at=now(),resolved_by=(SELECT id FROM users WHERE wallet_address=$1),resolution_note='integration test cleanup' WHERE status<>'RESOLVED' AND (source_reference LIKE 'integration-worker:%' OR source_reference LIKE 'it:%')`,[wallet]);await pool.end()});
 it("pauses/resumes idempotently and preserves append-only history",async()=>{const key=`operations:test:pause:${Date.now()}`,first=await pauseModule("AUTO_WITHDRAW_WORKER",wallet,"integration safety test","PAUSE_AUTO_WITHDRAW",key),again=await pauseModule("AUTO_WITHDRAW_WORKER",wallet,"integration safety test","PAUSE_AUTO_WITHDRAW",key);expect(first.is_paused).toBe(true);expect(again.is_paused).toBe(true);expect(await isModulePaused("AUTO_WITHDRAW_WORKER")).toBe(true);await expect(pool.query("UPDATE operations_admin_actions SET reason='changed' WHERE idempotency_key=$1",[key])).rejects.toThrow();const resumed=await resumeModule("AUTO_WITHDRAW_WORKER",wallet,"integration resume test","RESUME_AUTO_WITHDRAW",`operations:test:resume:${Date.now()}`);expect(resumed.is_paused).toBe(false)});
 it("records worker states and generates deduplicated stale alerts",async()=>{const instance=`it-${Date.now()}`;await recordHeartbeat({workerName:"integration-worker",instanceId:instance,status:"STARTING",intervalSeconds:10});await recordHeartbeat({workerName:"integration-worker",instanceId:instance,status:"IDLE",intervalSeconds:10,processed:2});await pool.query("UPDATE worker_heartbeats SET last_heartbeat_at=now()-interval '60 seconds' WHERE worker_name='integration-worker' AND instance_id=$1",[instance]);await refreshWorkerAlerts();await refreshWorkerAlerts();expect((await pool.query("SELECT count(*)::int count FROM operations_alerts WHERE alert_type='WORKER_HEARTBEAT_STALE' AND source_reference=$1 AND status<>'RESOLVED'",[`integration-worker:${instance}`])).rows[0].count).toBe(1)});
 it("deduplicates alerts and reconciliation is read-only",async()=>{const source=`it:${Date.now()}`;await upsertAlert({type:"TEST_ALERT",severity:"WARNING",module:null,title:"Test",description:"first",source});await upsertAlert({type:"TEST_ALERT",severity:"HIGH",module:null,title:"Test",description:"second",source});expect((await pool.query("SELECT count(*)::int count FROM operations_alerts WHERE alert_type='TEST_ALERT' AND source_reference=$1 AND status<>'RESOLVED'",[source])).rows[0].count).toBe(1);const before=(await pool.query("SELECT count(*)::text count FROM income_wallet_ledger")).rows[0].count;const result=await runDatabaseReconciliation(wallet);expect(result.runId).toBeTruthy();expect((await pool.query("SELECT count(*)::text count FROM income_wallet_ledger")).rows[0].count).toBe(before)});
});
