// @vitest-environment node
import{afterEach,describe,expect,it}from"vitest";import{NextRequest}from"next/server";import{proxy,resetRateLimitsForTests}from"@/proxy";
const original={NODE_ENV:process.env.NODE_ENV,APP_ORIGIN:process.env.APP_ORIGIN};afterEach(()=>{resetRateLimitsForTests();Object.assign(process.env,original)});
describe("production HTTP security policy",()=>{
 // @ts-expect-error test mutates the normally read-only NODE_ENV field
 it("sets browser security headers",async()=>{process.env.NODE_ENV="production";const response=await proxy(new NextRequest("https://app.example.com/api/health/live"));expect(response.headers.get("content-security-policy")).toContain("frame-ancestors 'none'");expect(response.headers.get("strict-transport-security")).toContain("includeSubDomains");expect(response.headers.get("x-content-type-options")).toBe("nosniff");expect(response.headers.get("permissions-policy")).toContain("camera=()")});
 it("rejects cross-origin API requests",async()=>{process.env.APP_ORIGIN="https://app.example.com";const response=await proxy(new NextRequest("https://app.example.com/api/auth/nonce",{method:"POST",headers:{origin:"https://evil.example","x-forwarded-for":"203.0.113.1"}}));expect(response.status).toBe(403);expect(await response.json()).toMatchObject({code:"ORIGIN_DENIED"})});
 it("rejects oversized request bodies before route parsing",async()=>{const response=await proxy(new NextRequest("https://app.example.com/api/auth/verify",{method:"POST",headers:{"content-length":"1048577","x-forwarded-for":"203.0.113.2"}}));expect(response.status).toBe(413);expect(await response.json()).toMatchObject({code:"PAYLOAD_TOO_LARGE"})});
 it("rate limits authentication independently by client address",async()=>{for(let i=0;i<30;i++)expect((await proxy(new NextRequest("https://app.example.com/api/auth/nonce",{headers:{"x-forwarded-for":"203.0.113.3"}}))).status).toBe(200);const blocked=await proxy(new NextRequest("https://app.example.com/api/auth/nonce",{headers:{"x-forwarded-for":"203.0.113.3"}}));expect(blocked.status).toBe(429);expect(blocked.headers.get("retry-after")).toBe("60");expect((await proxy(new NextRequest("https://app.example.com/api/auth/nonce",{headers:{"x-forwarded-for":"203.0.113.4"}}))).status).toBe(200)});
 it.each([["registration","/api/registrations/prepare",20],["admin","/api/admin/overview",120]])("rate limits %s endpoints",async(_,path,limit)=>{for(let index=0;index<limit;index++)expect((await proxy(new NextRequest(`https://app.example.com${path}`,{headers:{"x-forwarded-for":`198.51.100.${limit}`}}))).status).toBe(200);expect((await proxy(new NextRequest(`https://app.example.com${path}`,{headers:{"x-forwarded-for":`198.51.100.${limit}`}}))).status).toBe(429)});
});
