const {expect}=require("chai");const{ethers,artifacts}=require("hardhat");
describe("SmartEarning unified packages, matrices and treasury",function(){const dollar=1_000_000n;let token,registration,packages,admin,genesis,user,other,authorizer;
beforeEach(async function(){[admin,genesis,user,other,authorizer]=await ethers.getSigners();token=await(await ethers.getContractFactory("MockUSDT")).deploy();registration=await(await ethers.getContractFactory("SmartEarning")).deploy(await token.getAddress(),genesis.address,admin.address,admin.address,authorizer.address);packages=registration;for(const account of[user,other]){await token.mint(account.address,5000n*dollar);await token.connect(account).approve(await registration.getAddress(),5000n*dollar)}});
it("uses one deployable primary contract below the EIP-170 bytecode limit",async function(){const artifact=await artifacts.readArtifact("SmartEarning"),size=(artifact.deployedBytecode.length-2)/2;expect(size).to.be.lessThan(24_576);expect(size).to.be.greaterThan(0)});
async function register(account=user){await registration.connect(account).register(genesis.address)}
async function authorization(id="withdrawal-1",overrides={}){
 const network=await ethers.provider.getNetwork(),contract=await registration.getAddress(),now=(await ethers.provider.getBlock("latest")).timestamp;
 const value={payoutType:ethers.id("INCOME_WITHDRAWAL"),reservationId:ethers.id(id),earningSource:ethers.id("LEDGER"),user:user.address,chainId:network.chainId,verifyingContract:contract,grossAmount:1_000_000n,feeAmount:100_000n,netAmount:900_000n,destination:user.address,issuedAt:BigInt(now),nonce:1n,deadline:BigInt(now+3600),...overrides};
 const types={WithdrawalAuthorization:[
  {name:"payoutType",type:"bytes32"},{name:"reservationId",type:"bytes32"},{name:"earningSource",type:"bytes32"},{name:"user",type:"address"},{name:"chainId",type:"uint256"},{name:"verifyingContract",type:"address"},{name:"grossAmount",type:"uint256"},{name:"feeAmount",type:"uint256"},{name:"netAmount",type:"uint256"},{name:"destination",type:"address"},{name:"issuedAt",type:"uint256"},{name:"nonce",type:"uint256"},{name:"deadline",type:"uint256"}
 ]};
 return{value,signature:await authorizer.signTypedData({name:"SmartEarning",version:"1",chainId:network.chainId,verifyingContract:contract},types,value)};
}
it("rejects unregistered users",async function(){await expect(packages.connect(user).purchasePackage(1,8n*dollar)).to.be.revertedWithCustomError(packages,"SponsorNotRegistered")});
it("allows Package 1, records 12.5% Magic, and forwards the full payment",async function(){await register();const before=await token.balanceOf(admin.address);await expect(packages.connect(user).purchasePackage(1,8n*dollar)).to.emit(registration,"MagicFunded");expect(await token.balanceOf(admin.address)).to.equal(before+8n*dollar);expect(await token.balanceOf(await packages.getAddress())).to.equal(0);expect(await registration.magicBalance(user.address)).to.equal(2n*dollar);expect(await packages.hasPurchasedPackage(user.address,1)).to.equal(true)});
it("failed treasury forwarding reverts package state and user payment",async function(){await register();const userBefore=await token.balanceOf(user.address),capBefore=await registration.totalEarningCap(user.address);await token.setRejectedRecipient(admin.address);await expect(registration.connect(user).purchasePackage(1,8n*dollar)).to.be.revertedWith("REJECTED_RECIPIENT");expect(await token.balanceOf(user.address)).to.equal(userBefore);expect(await registration.hasPurchasedPackage(user.address,1)).to.equal(false);expect(await registration.totalEarningCap(user.address)).to.equal(capBefore);expect(await registration.magicBalance(user.address)).to.equal(dollar)});
it("failed X3/X4 placement pause reverts package and payment",async function(){await register();const before=await token.balanceOf(user.address);await registration.setPlacementPaused(true,false);await expect(registration.connect(user).purchasePackage(1,8n*dollar)).to.be.revertedWithCustomError(registration,"PlacementModulePaused");expect(await token.balanceOf(user.address)).to.equal(before);expect(await registration.hasPurchasedPackage(user.address,1)).to.equal(false)});
it("X4 A and B each record exactly 6.25% Magic accounting",async function(){const fifth=(await ethers.getSigners())[4];for(const account of[user,other,fifth]){if(account===fifth){await token.mint(account.address,20n*dollar);await token.connect(account).approve(await registration.getAddress(),20n*dollar)}await registration.connect(account).register(genesis.address)}await registration.connect(user).purchasePackage(1,8n*dollar);await expect(registration.connect(other).purchasePackage(1,8n*dollar)).to.emit(registration,"X4Placed").withArgs(other.address,user.address,1,1,1,500_000n,1);await expect(registration.connect(fifth).purchasePackage(1,8n*dollar)).to.emit(registration,"X4Placed").withArgs(fifth.address,user.address,1,2,1,500_000n,1)});
it("rejects skipping, duplicates, wrong IDs, and wrong amounts",async function(){await register();await expect(packages.connect(user).purchasePackage(2,16n*dollar)).to.be.revertedWithCustomError(packages,"WrongNextPackage");await expect(packages.connect(user).purchasePackage(9,1)).to.be.revertedWithCustomError(packages,"InvalidPackageId");await expect(packages.connect(user).purchasePackage(1,7n*dollar)).to.be.revertedWithCustomError(packages,"WrongPaymentAmount");await packages.connect(user).purchasePackage(1,8n*dollar);await expect(packages.connect(user).purchasePackage(1,8n*dollar)).to.be.revertedWithCustomError(packages,"PackageAlreadyPurchased")});
it("fails with insufficient allowance",async function(){await register(other);await token.connect(other).approve(await packages.getAddress(),0);await expect(packages.connect(other).purchasePackage(1,8n*dollar)).to.be.reverted});
it("returns the correct next package, totals, and 5X cap",async function(){await register();expect(await packages.getNextPackage(user.address)).to.equal(1);await packages.connect(user).purchasePackage(1,8n*dollar);expect(await packages.getNextPackage(user.address)).to.equal(2);expect(await packages.getTotalPackageValue(user.address)).to.equal(8n*dollar);expect(await packages.getTotalEligibleValue(user.address)).to.equal(10n*dollar);expect(await packages.getTotalEarningCap(user.address)).to.equal(50n*dollar)});
it("purchases all eight serially and then reaches maximum",async function(){await register();const values=[8n,16n,32n,64n,128n,256n,512n,1024n];for(let i=0;i<8;i++)await packages.connect(user).purchasePackage(i+1,values[i]*dollar);expect(await packages.getNextPackage(user.address)).to.equal(0);expect(await packages.getTotalPackageValue(user.address)).to.equal(2040n*dollar);expect(await packages.getTotalEligibleValue(user.address)).to.equal(2042n*dollar);expect(await packages.getTotalEarningCap(user.address)).to.equal(10210n*dollar);await expect(packages.connect(user).purchasePackage(8,1024n*dollar)).to.be.revertedWithCustomError(packages,"PackageAlreadyPurchased")});
it("blocks purchases while paused",async function(){await register();await packages.pause();await expect(packages.connect(user).purchasePackage(1,8n*dollar)).to.be.revertedWithCustomError(packages,"EnforcedPause")});
it("uses nonReentrant purchase entry and checks state before transfer",async function(){await register();await packages.connect(user).purchasePackage(1,8n*dollar);expect(await packages.highestPackageId(user.address)).to.equal(1);expect(await token.balanceOf(await packages.getAddress())).to.equal(0)});
it("keeps package purchase and 5X cap unchanged with sponsor-started placement",async function(){await register();await registration.connect(other).register(user.address);expect(await registration.matrixParentOf(other.address)).to.equal(user.address);const[left,right]=await registration.getMatrixChildren(user.address);expect(left).to.equal(other.address);expect(right).to.equal(ethers.ZeroAddress);await packages.connect(user).purchasePackage(1,8n*dollar);expect(await packages.getTotalPackageValue(user.address)).to.equal(8n*dollar);expect(await packages.getTotalEligibleValue(user.address)).to.equal(10n*dollar);expect(await packages.getTotalEarningCap(user.address)).to.equal(50n*dollar)});
it("caps existing income, records excess, and package purchase reactivates capacity",async function(){const signers=await ethers.getSigners();for(const account of signers.slice(4,15)){await token.mint(account.address,2n*dollar);await token.connect(account).approve(await registration.getAddress(),2n*dollar)}for(const account of signers.slice(4,14))await registration.connect(account).register(genesis.address);expect(await registration.totalEarned(genesis.address)).to.equal(10n*dollar);expect(await registration.getRemainingEarningCap(genesis.address)).to.equal(0);expect(await registration.getCappingStatus(genesis.address)).to.equal(2);await expect(registration.connect(signers[14]).register(genesis.address)).to.emit(registration,"IncomeCapped");expect(await registration.cappedExcess(genesis.address,ethers.keccak256(ethers.toUtf8Bytes("DIRECT_INCOME")))).to.equal(1n*dollar);await token.mint(genesis.address,8n*dollar);await token.connect(genesis).approve(await registration.getAddress(),8n*dollar);await registration.connect(genesis).purchasePackage(1,8n*dollar);expect(await registration.totalEarningCap(genesis.address)).to.equal(50n*dollar);expect(await registration.getRemainingEarningCap(genesis.address)).to.equal(40n*dollar);expect(await registration.getCappingStatus(genesis.address)).to.equal(0)});
it("treasury funds only net liquidity and pays one signed reservation exactly once",async function(){const funding=ethers.id("funding-1"),auth=await authorization();await token.mint(admin.address,900_000n);await token.connect(admin).approve(await registration.getAddress(),900_000n);await expect(registration.connect(admin).fundWithdrawalLiquidity(900_000n,funding)).to.emit(registration,"WithdrawalLiquidityFunded");const before=await token.balanceOf(user.address);await expect(registration.executeWithdrawal(auth.value,auth.signature)).to.emit(registration,"WithdrawalPaid");expect(await token.balanceOf(user.address)).to.equal(before+900_000n);expect(await token.balanceOf(await registration.getAddress())).to.equal(0);await expect(registration.executeWithdrawal(auth.value,auth.signature)).to.be.revertedWithCustomError(registration,"WithdrawalAlreadyProcessed")});
it("liquidity sources and withdrawal executor are access controlled",async function(){const funding=ethers.id("funding-role"),auth=await authorization();await token.mint(admin.address,900_000n);await token.connect(admin).approve(await registration.getAddress(),900_000n);await registration.fundWithdrawalLiquidity(900_000n,funding);await expect(registration.fundWithdrawalLiquidity(900_000n,funding)).to.be.revertedWithCustomError(registration,"FundingAlreadyProcessed");await expect(registration.connect(user).executeWithdrawal(auth.value,auth.signature)).to.be.reverted});
it("withdrawal fails safely for insufficient liquidity and while paused",async function(){const auth=await authorization("withdrawal-2");await expect(registration.executeWithdrawal(auth.value,auth.signature)).to.be.revertedWithCustomError(registration,"InsufficientWithdrawalLiquidity");expect(await registration.processedWithdrawals(await registration.withdrawalAuthorizationHash(auth.value))).to.equal(false);await registration.setWithdrawalsPaused(true);await expect(registration.executeWithdrawal(auth.value,auth.signature)).to.be.revertedWithCustomError(registration,"WithdrawalsPaused")});
it("rejects zero treasury and unauthorized treasury updates",async function(){const factory=await ethers.getContractFactory("SmartEarning");await expect(factory.deploy(await token.getAddress(),genesis.address,admin.address,ethers.ZeroAddress,authorizer.address)).to.be.revertedWithCustomError(registration,"ZeroAddress");await expect(registration.connect(user).setTreasuryWallet(user.address)).to.be.reverted});
it("authorized treasury change emits old, new and actor",async function(){await expect(registration.setTreasuryWallet(other.address)).to.emit(registration,"TreasuryWalletUpdated").withArgs(admin.address,other.address,admin.address)});
it("tops up Booster atomically and forwards the full amount without financial side effects",async function(){await register();const source=ethers.keccak256(ethers.toUtf8Bytes("booster-topup-1")),amount=5n*dollar,treasuryBefore=await token.balanceOf(admin.address),cap=await registration.totalEarningCap(user.address),magic=await registration.magicBalance(user.address),packagesBefore=await registration.totalPackageValue(user.address);await expect(registration.connect(user).topupBooster(amount,source)).to.emit(registration,"BoosterTopup").withArgs(user.address,amount,source);expect(await token.balanceOf(admin.address)).to.equal(treasuryBefore+amount);expect(await token.balanceOf(await registration.getAddress())).to.equal(0);expect(await registration.totalEarningCap(user.address)).to.equal(cap);expect(await registration.magicBalance(user.address)).to.equal(magic);expect(await registration.totalPackageValue(user.address)).to.equal(packagesBefore);expect(await registration.x3CycleNumber(1,user.address)).to.equal(0);expect(await registration.x4CycleNumber(1,user.address)).to.equal(0)});
it("rejects duplicate Booster sources and unregistered top-ups",async function(){const source=ethers.keccak256(ethers.toUtf8Bytes("booster-topup-duplicate"));await expect(registration.connect(user).topupBooster(dollar,source)).to.be.revertedWithCustomError(registration,"SponsorNotRegistered");await register();await registration.connect(user).topupBooster(dollar,source);await expect(registration.connect(user).topupBooster(dollar,source)).to.be.revertedWithCustomError(registration,"PaymentSourceAlreadyProcessed")});
it("reverts the complete Booster top-up when treasury forwarding fails",async function(){await register();const source=ethers.keccak256(ethers.toUtf8Bytes("booster-topup-fail")),before=await token.balanceOf(user.address);await token.setRejectedRecipient(admin.address);await expect(registration.connect(user).topupBooster(dollar,source)).to.be.revertedWith("REJECTED_RECIPIENT");expect(await token.balanceOf(user.address)).to.equal(before);expect(await registration.processedPaymentSources(source)).to.equal(false);expect(await token.balanceOf(await registration.getAddress())).to.equal(0)});
});
