const{expect}=require("chai");const{ethers}=require("hardhat");
describe("SmartEarning aligned direct-referral X3",function(){
 const dollar=1_000_000n;let contract,token,admin,authorizer,genesis,owner,b1,b2,b3,b4,outsider;
 async function prepare(account,sponsor){await token.mint(account.address,100n*dollar);await token.connect(account).approve(await contract.getAddress(),100n*dollar);await contract.connect(account).register(sponsor.address)}
 beforeEach(async function(){[admin,authorizer,genesis,owner,b1,b2,b3,b4,outsider]=await ethers.getSigners();token=await(await ethers.getContractFactory("MockUSDT")).deploy();contract=await(await ethers.getContractFactory("SmartEarning")).deploy(await token.getAddress(),genesis.address,admin.address,admin.address,authorizer.address);await prepare(owner,genesis);for(const buyer of[b1,b2,b3,b4])await prepare(buyer,owner);await prepare(outsider,b1)});
 it("fills only direct buyers into slots 1/2/3 and opens cycle 2",async function(){
  await expect(contract.connect(b1).purchasePackage(1,8n*dollar)).to.emit(contract,"X3DirectSlotFilled").withArgs(b1.address,owner.address,1,1,1,owner.address,0,8n*dollar,2n*dollar);
  await expect(contract.connect(b2).purchasePackage(1,8n*dollar)).to.emit(contract,"X3DirectSlotFilled").withArgs(b2.address,owner.address,1,1,2,owner.address,0,8n*dollar,2n*dollar);
  await expect(contract.connect(b3).purchasePackage(1,8n*dollar)).to.emit(contract,"X3DirectSlotFilled").withArgs(b3.address,owner.address,1,1,3,genesis.address,1,8n*dollar,2n*dollar).and.to.emit(contract,"X3DirectCycleCompleted").withArgs(owner.address,1,1,2);
  expect(await contract.x3DirectCycleNumber(1,owner.address)).to.equal(2);expect(await contract.x3DirectSlotCount(1,owner.address)).to.equal(0);expect(await contract.x3DirectCycleNumber(1,genesis.address)).to.equal(0);
  await expect(contract.connect(b4).purchasePackage(1,8n*dollar)).to.emit(contract,"X3DirectSlotFilled").withArgs(b4.address,owner.address,1,2,1,owner.address,0,8n*dollar,2n*dollar);
 });
 it("does not spill a non-direct buyer into the owner's cycle",async function(){await contract.connect(outsider).purchasePackage(1,8n*dollar);expect(await contract.x3DirectSlotCount(1,owner.address)).to.equal(0);expect(await contract.x3DirectSlotCount(1,b1.address)).to.equal(1)});
 it("keeps packages independent and serial order enforced",async function(){await contract.connect(b1).purchasePackage(1,8n*dollar);await expect(contract.connect(b1).purchasePackage(2,16n*dollar)).to.emit(contract,"X3DirectSlotFilled").withArgs(b1.address,owner.address,2,1,1,owner.address,0,16n*dollar,4n*dollar);expect(await contract.x3DirectSlotCount(1,owner.address)).to.equal(1);expect(await contract.x3DirectSlotCount(2,owner.address)).to.equal(1);await expect(contract.connect(b1).purchasePackage(2,16n*dollar)).to.be.revertedWithCustomError(contract,"PackageAlreadyPurchased")});
 it("records genesis safely without self-credit or cycle state",async function(){await token.mint(genesis.address,8n*dollar);await token.connect(genesis).approve(await contract.getAddress(),8n*dollar);await expect(contract.connect(genesis).purchasePackage(1,8n*dollar)).to.emit(contract,"X3DirectSlotFilled").withArgs(genesis.address,ethers.ZeroAddress,1,0,0,ethers.ZeroAddress,2,8n*dollar,2n*dollar);expect(await contract.x3DirectCycleNumber(1,genesis.address)).to.equal(0);expect(await contract.x3DirectSlotCount(1,genesis.address)).to.equal(0)});
 it("creates no on-chain X3 cap, earned, or split effect",async function(){const ownerEarned=await contract.totalEarned(owner.address),ownerMagic=await contract.magicBalance(owner.address);await contract.connect(b1).purchasePackage(1,8n*dollar);await contract.connect(b2).purchasePackage(1,8n*dollar);expect(await contract.totalEarned(owner.address)).to.equal(ownerEarned);expect(await contract.magicBalance(owner.address)).to.equal(ownerMagic)});
});
