// @vitest-environment node
import{afterAll,beforeAll,describe,expect,it}from"vitest";
import{Pool,PoolClient}from"pg";import{randomUUID}from"node:crypto";
import{processDirectX3PackagePurchase,isDirectX3Purchase,ensureCurrentDirectX3Alignment}from"@/lib/server/x3-direct-service";
import{smartEarningDeployment}from"@/lib/blockchain/deployment-metadata";
import{releaseHeldX3}from"@/lib/server/x3-service";
import{runX3HoldExpiryScheduler}from"@/lib/server/x3-hold-expiry-service";

const url=process.env.X3_DIRECT_TEST_DATABASE_URL,db=url?describe:describe.skip;
let pool:Pool,serial=0;const dollar=1_000_000n;
const wallet=()=>`0x${randomUUID().replaceAll("-","").padEnd(40,"0").slice(0,40)}`,tx=()=>`0x${randomUUID().replaceAll("-","").padEnd(64,"0")}`;

async function user(client:PoolClient,sponsor?:string){
 const id=(await client.query<{id:string}>("INSERT INTO users(wallet_address) VALUES($1) RETURNING id",[wallet()])).rows[0].id;
 await client.query("INSERT INTO user_package_states(user_id,registration_value,total_package_value,total_eligible_value,total_earning_cap,total_earned,remaining_cap,capping_status) VALUES($1,2000000,0,0,0,0,0,'NOT_APPLICABLE')",[id]);
 if(sponsor){const reg=(await client.query<{id:string}>(`INSERT INTO registrations(user_id,sponsor_user_id,tx_hash,chain_id,amount_token_units,status) VALUES($1,$2,$3,97,2000000,'CONFIRMED') RETURNING id`,[id,sponsor,tx()])).rows[0].id;await client.query("INSERT INTO referral_relations(user_id,sponsor_user_id,registration_id) VALUES($1,$2,$3)",[id,sponsor,reg]);}
 return id;
}
async function purchase(client:PoolClient,buyer:string,packageId=1,block=100,log=0){
 block=smartEarningDeployment().blockNumber+block;
 const amount=8n*(1n<<BigInt(packageId-1))*dollar,hash=tx(),def=(await client.query<{id:string}>("SELECT id FROM package_definitions WHERE serial_number=$1",[packageId])).rows[0].id;
 const p=(await client.query<{id:string}>(`INSERT INTO package_purchases(user_id,wallet_address,package_definition_id,package_id,amount_token_units,tx_hash,block_number,status,purchased_at,confirmed_block_at) SELECT $1,wallet_address,$2,$3,$4,$5,$6,'CONFIRMED',now(),now() FROM users WHERE id=$1 RETURNING id`,[buyer,def,packageId,amount.toString(),hash,block])).rows[0].id;
 await client.query(`UPDATE user_package_states SET total_package_value=$2::numeric,total_eligible_value=$2::numeric,
   total_earning_cap=$2::numeric*5,remaining_cap=GREATEST($2::numeric*5-total_earned,0),
   capping_status=CASE WHEN total_earned >= $2::numeric*5 THEN 'CAPPED' ELSE 'ACTIVE' END WHERE user_id=$1`,
 [buyer,amount.toString()]);
 const e=(await client.query<{id:string}>(`INSERT INTO contract_events(chain_id,contract_address,tx_hash,log_index,block_number,block_hash,event_name,payload) VALUES(97,$1,$2,$3,$4,$5,'PackagePurchased','{}') RETURNING id`,[`0x${"9".repeat(40)}`,hash,log,block,`0x${"8".repeat(64)}`])).rows[0].id;
 return{purchaseId:p,userId:buyer,packageId,amount,txHash:hash,blockNumber:block,sourceEventId:e,logIndex:log};
}
async function qualify(client:PoolClient,id:string,packageId=1){const p=await purchase(client,id,packageId,50+serial,0);await client.query("INSERT INTO x3_package_memberships(user_id,package_id,activation_purchase_id,activated_at) VALUES($1,$2,$3,now())",[id,packageId,p.purchaseId]);return p;}
async function aligned(client:PoolClient,_b=90){await ensureCurrentDirectX3Alignment(client);}
async function setup(client:PoolClient,qualifyRecipients=true){const genesis=await user(client),passup=await user(client,genesis),owner=await user(client,passup),buyers=[await user(client,owner),await user(client,owner),await user(client,owner),await user(client,owner)];if(qualifyRecipients){await qualify(client,owner);await qualify(client,passup)}await aligned(client);return{genesis,passup,owner,buyers};}

db.sequential("direct-referral X3 on PostgreSQL",()=>{
 beforeAll(()=>{process.env.AUTO_WITHDRAW_ENABLED="false";pool=new Pool({connectionString:url,max:8})});afterAll(async()=>{if(pool)await pool.end()});

 it("fills slots 1/2/3, passes up slot 3, completes and opens the next cycle",async()=>{const c=await pool.connect();await c.query("BEGIN");try{const f=await setup(c);for(let i=0;i<3;i++)await processDirectX3PackagePurchase(c,await purchase(c,f.buyers[i],1,100+i,i));const cycles=await c.query("SELECT cycle_number,status FROM x3_direct_cycles WHERE owner_user_id=$1 ORDER BY cycle_number",[f.owner]);expect(cycles.rows).toEqual([{cycle_number:1,status:"COMPLETED"},{cycle_number:2,status:"ACTIVE"}]);const slots=await c.query("SELECT slot_number,buyer_user_id,recipient_user_id,disposition FROM x3_direct_cycle_slots s JOIN x3_direct_cycles c ON c.id=s.cycle_id WHERE c.owner_user_id=$1 ORDER BY slot_number",[f.owner]);expect(slots.rows).toEqual([{slot_number:1,buyer_user_id:f.buyers[0],recipient_user_id:f.owner,disposition:"OWNER_INCOME"},{slot_number:2,buyer_user_id:f.buyers[1],recipient_user_id:f.owner,disposition:"OWNER_INCOME"},{slot_number:3,buyer_user_id:f.buyers[2],recipient_user_id:f.passup,disposition:"PASS_UP"}]);expect((await c.query("SELECT count(*)::int n FROM x3_direct_cycle_slots s JOIN x3_direct_cycles c ON c.id=s.cycle_id WHERE c.owner_user_id=$1",[f.passup])).rows[0].n).toBe(0)}finally{await c.query("ROLLBACK");c.release()}});

 it("does not fill slots for registration, deposit-style ledger activity, or top-up",async()=>{const c=await pool.connect();await c.query("BEGIN");try{const f=await setup(c),registered=await user(c,f.owner);await c.query(`INSERT INTO booster_wallet_ledger(user_id,direction,amount_token_units,reason,idempotency_key) VALUES($1,'CREDIT',5000000,'MANUAL_TOP_UP',$2)`,[registered,`x3-no-fill:${randomUUID()}`]);expect((await c.query("SELECT count(*)::int n FROM x3_direct_cycle_slots s JOIN x3_direct_cycles x ON x.id=s.cycle_id WHERE x.owner_user_id=$1",[f.owner])).rows[0].n).toBe(0)}finally{await c.query("ROLLBACK");c.release()}});

 it("keeps non-direct buyers and packages isolated",async()=>{const c=await pool.connect();await c.query("BEGIN");try{const f=await setup(c),outsider=await user(c,f.buyers[0]);await processDirectX3PackagePurchase(c,await purchase(c,outsider));await processDirectX3PackagePurchase(c,await purchase(c,f.buyers[0],2,110,0));expect((await c.query("SELECT count(*)::int n FROM x3_direct_cycle_slots s JOIN x3_direct_cycles c ON c.id=s.cycle_id WHERE c.owner_user_id=$1",[f.owner])).rows[0].n).toBe(1);expect((await c.query("SELECT package_id FROM x3_direct_cycles WHERE owner_user_id=$1",[f.owner])).rows.map(x=>x.package_id)).toEqual([2]);expect((await c.query("SELECT count(*)::int n FROM x3_direct_cycle_slots s JOIN x3_direct_cycles c ON c.id=s.cycle_id WHERE c.owner_user_id=$1",[f.buyers[0]])).rows[0].n).toBe(1)}finally{await c.query("ROLLBACK");c.release()}});

 it("credits owner and pass-up through one cap and one 90/10 split",async()=>{const c=await pool.connect();await c.query("BEGIN");try{const f=await setup(c);for(let i=0;i<3;i++)await processDirectX3PackagePurchase(c,await purchase(c,f.buyers[i],1,120+i,i));const owner=await c.query(`SELECT count(*)::int splits,sum(e.magic_amount)::text magic,sum(e.income_amount)::text income FROM earning_split_events e WHERE e.user_id=$1 AND e.income_type='X3_PACKAGE'`,[f.owner]);expect(owner.rows[0]).toEqual({splits:2,magic:"400000",income:"3600000"});const pass=await c.query(`SELECT count(*)::int splits,sum(e.magic_amount)::text magic,sum(e.income_amount)::text income FROM earning_split_events e WHERE e.user_id=$1 AND e.income_type='X3_PACKAGE'`,[f.passup]);expect(pass.rows[0]).toEqual({splits:1,magic:"200000",income:"1800000"})}finally{await c.query("ROLLBACK");c.release()}});

 it("creates timed owner and pass-up holds and releases only before expiry",async()=>{const c=await pool.connect();await c.query("BEGIN");try{const f=await setup(c,false);for(let i=0;i<3;i++)await processDirectX3PackagePurchase(c,await purchase(c,f.buyers[i],1,130+i,i));const holds=await c.query("SELECT user_id,held_at,expires_at FROM x3_hold_ledger ORDER BY held_at");expect(holds.rows.map(x=>x.user_id)).toEqual([f.owner,f.owner,f.passup]);expect(holds.rows.every(x=>x.expires_at.getTime()-x.held_at.getTime()===172_800_000)).toBe(true);const first=await c.query<{expires_at:Date}>("SELECT expires_at FROM x3_hold_ledger WHERE user_id=$1 ORDER BY held_at LIMIT 1",[f.owner]),release=await qualify(c,f.owner);await releaseHeldX3(c,f.owner,1,release.purchaseId,new Date(first.rows[0].expires_at.getTime()-1));expect((await c.query("SELECT count(*)::int n FROM x3_hold_ledger WHERE user_id=$1 AND status IN('RELEASED','PARTIALLY_CAPPED')",[f.owner])).rows[0].n).toBe(2);expect((await c.query("SELECT count(*)::int n FROM x3_hold_release_history WHERE user_id=$1",[f.owner])).rows[0].n).toBe(2)}finally{await c.query("ROLLBACK");c.release()}});

 it("flushes at the exact boundary and never revives",async()=>{const c=await pool.connect();await c.query("BEGIN");try{const f=await setup(c,false);await processDirectX3PackagePurchase(c,await purchase(c,f.buyers[0],1,140,0));const h=(await c.query<{id:string;expires_at:Date}>("SELECT id,expires_at FROM x3_hold_ledger WHERE user_id=$1",[f.owner])).rows[0],p=await qualify(c,f.owner);await releaseHeldX3(c,f.owner,1,p.purchaseId,h.expires_at);expect((await c.query("SELECT status FROM x3_hold_ledger WHERE id=$1",[h.id])).rows[0].status).toBe("FLUSHED");await releaseHeldX3(c,f.owner,1,p.purchaseId,new Date(h.expires_at.getTime()-1000));expect((await c.query("SELECT status FROM x3_hold_ledger WHERE id=$1",[h.id])).rows[0].status).toBe("FLUSHED")}finally{await c.query("ROLLBACK");c.release()}});

 it("preserves cap and records capped excess",async()=>{const c=await pool.connect();await c.query("BEGIN");try{const f=await setup(c);await c.query("UPDATE user_package_states SET total_earned=39000000,remaining_cap=1000000 WHERE user_id=$1",[f.owner]);await processDirectX3PackagePurchase(c,await purchase(c,f.buyers[0],1,150,0));expect((await c.query("SELECT credited_amount::text,excess_amount::text,status FROM x3_direct_income_ledger WHERE recipient_user_id=$1",[f.owner])).rows[0]).toEqual({credited_amount:"1000000",excess_amount:"1000000",status:"CAPPED"});expect((await c.query("SELECT excess_amount::text FROM capped_excess_ledger WHERE user_id=$1",[f.owner])).rows[0].excess_amount).toBe("1000000")}finally{await c.query("ROLLBACK");c.release()}});

 it("rejects duplicate purchase and rolls failed transactions back without partial finance",async()=>{const c=await pool.connect();try{await c.query("BEGIN");const f=await setup(c),p=await purchase(c,f.buyers[0],1,160,0);await processDirectX3PackagePurchase(c,p);expect((await processDirectX3PackagePurchase(c,p)).duplicate).toBe(true);expect((await c.query("SELECT count(*)::int n FROM earning_split_events WHERE user_id=$1 AND income_type='X3_PACKAGE'",[f.owner])).rows[0].n).toBe(1);await c.query("ROLLBACK");expect((await pool.query("SELECT count(*)::int n FROM x3_direct_cycle_slots WHERE buyer_package_purchase_id=$1",[p.purchaseId])).rows[0].n).toBe(0)}finally{c.release()}});

 it("serializes concurrent direct buyers into distinct slots",async()=>{const seed=await pool.connect();await seed.query("BEGIN");const f=await setup(seed),p1=await purchase(seed,f.buyers[0],1,170,0),p2=await purchase(seed,f.buyers[1],1,171,0);await seed.query("COMMIT");seed.release();const a=await pool.connect(),b=await pool.connect();try{await a.query("BEGIN");await b.query("BEGIN");const one=await processDirectX3PackagePurchase(a,p1),twoPromise=processDirectX3PackagePurchase(b,p2);await a.query("COMMIT");const two=await twoPromise;await b.query("COMMIT");expect([one.slot,two.slot]).toEqual([1,2])}finally{await a.query("ROLLBACK").catch(()=>{});await b.query("ROLLBACK").catch(()=>{});a.release();b.release()}});

 it("enforces deployment identity and alignment safety",async()=>{const c=await pool.connect();await c.query("BEGIN");try{const d=smartEarningDeployment();await aligned(c);await c.query("UPDATE x3_direct_deployment_rollouts SET mode='TRANSITIONAL' WHERE chain_id=$1 AND contract_address=$2",[d.chainId,d.address]);await expect(isDirectX3Purchase(c,d.blockNumber,0)).rejects.toMatchObject({code:"X3_CONTRACT_ALIGNMENT_REQUIRED"});await aligned(c);expect(await isDirectX3Purchase(c,d.blockNumber,0)).toBe(true)}finally{await c.query("ROLLBACK");c.release()}});

 it("keeps completed snapshots immutable and legacy recovery structurally isolated",async()=>{const c=await pool.connect();await c.query("BEGIN");try{const f=await setup(c);for(let i=0;i<3;i++)await processDirectX3PackagePurchase(c,await purchase(c,f.buyers[i],1,180+i,i));const cycle=(await c.query("SELECT id FROM x3_direct_cycles WHERE owner_user_id=$1 AND cycle_number=1",[f.owner])).rows[0].id,slot=(await c.query("SELECT id FROM x3_direct_cycle_slots WHERE cycle_id=$1 LIMIT 1",[cycle])).rows[0].id;await c.query("SAVEPOINT immutable_cycle");await expect(c.query("UPDATE x3_direct_cycles SET completed_at=now() WHERE id=$1",[cycle])).rejects.toThrow(/immutable/);await c.query("ROLLBACK TO SAVEPOINT immutable_cycle");await c.query("SAVEPOINT immutable_slot");await expect(c.query("DELETE FROM x3_direct_cycle_slots WHERE id=$1",[slot])).rejects.toThrow(/append-only/);await c.query("ROLLBACK TO SAVEPOINT immutable_slot");expect((await c.query(`SELECT count(*)::int n FROM information_schema.columns WHERE table_name='x3_recovery_schedule' AND column_name LIKE '%direct%'`)).rows[0].n).toBe(0)}finally{await c.query("ROLLBACK").catch(()=>{});c.release()}});
});
