import type{PoolClient}from"pg";import{creditIncomeWithCap as applyIncomeCap}from"./income-cap-service";import{enqueueAutomaticWithdrawal}from"./withdrawal-service";
export const SPLIT_INCOME_TYPES=["DIRECT_INCOME","MAGIC_LEVEL_INCOME","X3_PACKAGE","X3_HOLD_RELEASE","X4_GLOBAL","BOOSTER","GLOBAL_AUTOPOOL","DAILY_DIVIDEND"] as const;
export function calculateEarningSplit(cappedGross:bigint){if(cappedGross<0n)throw new RangeError("Gross credit cannot be negative");const magic=cappedGross/10n;return{magic,income:cappedGross-magic}}
export async function creditGrossEarning(input:{userId:string;incomeType:string;sourceReference:string;grossAmount:bigint;idempotencyKey:string;countsForDividendComparison?:boolean;magicAlreadyOnchain?:boolean;confirmedOnchainCredit?:bigint},client:PoolClient){
 const existing=(await client.query<{id:string;income_credit_ledger_id:string;capped_gross_credit:string;capped_excess:string;magic_amount:string;income_amount:string}>(`SELECT id,income_credit_ledger_id,capped_gross_credit::text,capped_excess::text,magic_amount::text,income_amount::text FROM earning_split_events WHERE idempotency_key=$1`,[input.idempotencyKey])).rows[0];
 if(existing)return{splitEventId:existing.id,ledgerId:existing.income_credit_ledger_id,credited:BigInt(existing.capped_gross_credit),excess:BigInt(existing.capped_excess),magic:BigInt(existing.magic_amount),income:BigInt(existing.income_amount),duplicate:true};
 const capped=input.confirmedOnchainCredit===undefined
  ?await applyIncomeCap({userId:input.userId,incomeType:input.incomeType,sourceReference:input.sourceReference,calculatedAmount:input.grossAmount,idempotencyKey:`${input.idempotencyKey}:cap`},client)
  :await recordConfirmedOnchainCredit(client,input);
 const{magic,income}=calculateEarningSplit(capped.credited);
 const split=(await client.query<{id:string}>(`INSERT INTO earning_split_events(user_id,income_credit_ledger_id,income_type,source_reference,gross_calculated,capped_gross_credit,capped_excess,magic_amount,income_amount,counts_for_dividend_comparison,idempotency_key) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING id`,[input.userId,capped.ledgerId,input.incomeType,input.sourceReference,input.grossAmount.toString(),capped.credited.toString(),capped.excess.toString(),magic.toString(),income.toString(),input.countsForDividendComparison!==false,input.idempotencyKey])).rows[0];
 if(income>0n)await client.query(`INSERT INTO income_wallet_ledger(user_id,split_event_id,direction,amount,reason,idempotency_key,metadata) VALUES($1,$2,'CREDIT',$3,'EARNING_NET',$4,$5)`,[input.userId,split.id,income.toString(),`${input.idempotencyKey}:income`,JSON.stringify({incomeType:input.incomeType,sourceReference:input.sourceReference})]);
 if(magic>0n){const funding=(await client.query<{id:string}>(`INSERT INTO magic_funding_events(user_id,source_type,source_reference,amount,status,idempotency_key) VALUES($1,$2,$3,$4,'PENDING',$5) RETURNING id`,[input.userId,"EARNING_SPLIT",`${input.incomeType}:${input.sourceReference}`,magic.toString(),`${input.idempotencyKey}:magic`])).rows[0];if(input.magicAlreadyOnchain){const ledger=(await client.query<{id:string}>(`INSERT INTO magic_wallet_ledger(user_id,direction,amount_token_units,reason,idempotency_key,metadata) VALUES($1,'CREDIT',$2,'EARNING_10_PERCENT',$3,$4) RETURNING id`,[input.userId,magic.toString(),`${input.idempotencyKey}:magic-ledger`,JSON.stringify({incomeType:input.incomeType,sourceReference:input.sourceReference})])).rows[0];await client.query("UPDATE magic_funding_events SET status='CONFIRMED',magic_wallet_ledger_id=$2,onchain_amount=amount,updated_at=now() WHERE id=$1",[funding.id,ledger.id])}else await client.query("INSERT INTO magic_funding_outbox(funding_event_id) VALUES($1)",[funding.id])}
 if(income>0n)await enqueueAutomaticWithdrawal(client,input.userId);
 return{splitEventId:split.id,ledgerId:capped.ledgerId,credited:capped.credited,excess:capped.excess,magic,income,duplicate:false};
}
async function recordConfirmedOnchainCredit(client:PoolClient,input:{userId:string;incomeType:string;sourceReference:string;grossAmount:bigint;idempotencyKey:string;confirmedOnchainCredit?:bigint}){
 const credited=input.confirmedOnchainCredit!;
 if(credited<0n||credited>input.grossAmount)throw new RangeError("Confirmed credit must be within gross amount");
 const state=(await client.query<{total_earning_cap:string;total_earned:string}>(`SELECT total_earning_cap::text,total_earned::text FROM user_package_states WHERE user_id=$1 FOR UPDATE`,[input.userId])).rows[0];
 if(!state)throw new Error("Confirmed earning user cap state is not initialized");
 const cap=BigInt(state.total_earning_cap),earned=BigInt(state.total_earned),remainingBefore=cap>earned?cap-earned:0n,totalEarned=earned+credited;
 if(credited>remainingBefore)throw new Error(
  `Confirmed on-chain credit exceeds projected earning cap (user=${input.userId}, confirmed=${credited}, projectedCap=${cap}, projectedEarned=${earned})`
 );
 const excess=input.grossAmount-credited,remaining=cap>totalEarned?cap-totalEarned:0n,status=cap===0n?"NOT_APPLICABLE":remaining===0n?"CAPPED":totalEarned*100n>=cap*90n?"NEAR_CAP":"ACTIVE";
 const ledger=(await client.query<{id:string}>(`INSERT INTO income_credit_ledger(user_id,income_type,source_reference,calculated_amount,credited_amount,excess_amount,total_earned_after,idempotency_key) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id`,[input.userId,input.incomeType,input.sourceReference,input.grossAmount.toString(),credited.toString(),excess.toString(),totalEarned.toString(),`${input.idempotencyKey}:cap`])).rows[0];
 if(excess>0n)await client.query(`INSERT INTO capped_excess_ledger(user_id,income_type,source_reference,calculated_amount,credited_amount,excess_amount) VALUES($1,$2,$3,$4,$5,$6)`,[input.userId,input.incomeType,input.sourceReference,input.grossAmount.toString(),credited.toString(),excess.toString()]);
 await client.query(`UPDATE user_package_states SET total_earned=$2,remaining_cap=$3,capping_status=$4,updated_at=now() WHERE user_id=$1`,[input.userId,totalEarned.toString(),remaining.toString(),status]);
 return{credited,excess,totalEarned,ledgerId:ledger.id,duplicate:false};
}
export async function recordConfirmedMagicFunding(client:PoolClient,input:{userId:string;sourceType:string;sourceReference:string;amount:bigint;reason:string;idempotencyKey:string;txHash?:string}){const existing=await client.query("SELECT 1 FROM magic_funding_events WHERE source_reference=$1",[input.sourceReference]);if(existing.rowCount)return{duplicate:true};const ledger=(await client.query<{id:string}>(`INSERT INTO magic_wallet_ledger(user_id,direction,amount_token_units,reason,idempotency_key,metadata) VALUES($1,'CREDIT',$2,$3,$4,$5) RETURNING id`,[input.userId,input.amount.toString(),input.reason,`${input.idempotencyKey}:ledger`,JSON.stringify({sourceReference:input.sourceReference,txHash:input.txHash})])).rows[0];await client.query(`INSERT INTO magic_funding_events(user_id,source_type,source_reference,amount,status,magic_wallet_ledger_id,tx_hash,onchain_amount,idempotency_key) VALUES($1,$2,$3,$4,'CONFIRMED',$5,$6,$4,$7)`,[input.userId,input.sourceType,input.sourceReference,input.amount.toString(),ledger.id,input.txHash||null,input.idempotencyKey]);return{duplicate:false}}
export async function queueMagicFunding(client:PoolClient,input:{userId:string;sourceType:string;sourceReference:string;amount:bigint;idempotencyKey:string}){const prior=(await client.query<{id:string}>("SELECT id FROM magic_funding_events WHERE source_reference=$1",[input.sourceReference])).rows[0];if(prior)return{fundingEventId:prior.id,duplicate:true};const event=(await client.query<{id:string}>(`INSERT INTO magic_funding_events(user_id,source_type,source_reference,amount,status,idempotency_key) VALUES($1,$2,$3,$4,'PENDING',$5) RETURNING id`,[input.userId,input.sourceType,input.sourceReference,input.amount.toString(),input.idempotencyKey])).rows[0];await client.query("INSERT INTO magic_funding_outbox(funding_event_id) VALUES($1)",[event.id]);return{fundingEventId:event.id,duplicate:false}}
export async function creditIncomeWithCap(input:{userId:string;incomeType:string;sourceReference:string;calculatedAmount:bigint;idempotencyKey:string},client:PoolClient){return creditGrossEarning({userId:input.userId,incomeType:input.incomeType,sourceReference:input.sourceReference,grossAmount:input.calculatedAmount,idempotencyKey:input.idempotencyKey},client)}
