import type{PoolClient}from"pg";import{query,transaction}from"./db";import{ApiError}from"./http";import{assertConfiguredAdmin}from"./admin-policy";
export const OPERATION_MODULES=["MAGIC_FUNDING_WORKER","MAGIC_DISTRIBUTION_WORKER","DIVIDEND_WORKER","BOOSTER_WORKER","GLOBAL_AUTOPOOL_WORKER","AUTO_WITHDRAW_WORKER","WITHDRAWAL_BROADCAST","X3_PLACEMENT","X4_PLACEMENT","PACKAGE_PURCHASE"]as const;
export type OperationModule=typeof OPERATION_MODULES[number];
export function isOperationModule(value:string):value is OperationModule{return(OPERATION_MODULES as readonly string[]).includes(value)}
async function adminId(client:PoolClient,wallet:string){const normalized=assertConfiguredAdmin(wallet),row=(await client.query<{id:string}>("SELECT id FROM users WHERE wallet_address=$1",[normalized])).rows[0];if(!row)throw new ApiError(403,"Administrator user record required","ADMIN_USER_REQUIRED");return row.id}
export async function isModulePaused(moduleName:OperationModule,client?:PoolClient){const run=(c:PoolClient)=>c.query<{is_paused:boolean}>("SELECT is_paused FROM system_module_controls WHERE module_name=$1",[moduleName]).then(r=>r.rows[0]?.is_paused??false);return client?run(client):transaction(run)}
export async function assertModuleActive(moduleName:OperationModule,client?:PoolClient){if(await isModulePaused(moduleName,client))throw new ApiError(503,`${moduleName} is paused`,"MODULE_PAUSED")}
export async function getAllModuleStates(){return(await query(`SELECT c.*,p.wallet_address paused_by_wallet,r.wallet_address resumed_by_wallet FROM system_module_controls c LEFT JOIN users p ON p.id=c.paused_by LEFT JOIN users r ON r.id=c.resumed_by ORDER BY c.module_name`)).rows}
export async function setModuleState(input:{moduleName:OperationModule;paused:boolean;adminWallet:string;reason:string;confirmationPhrase:string;requestMetadata?:Record<string,unknown>;idempotencyKey:string}){
 if(input.reason.trim().length<3)throw new ApiError(400,"Reason is required","REASON_REQUIRED");const required=`${input.paused?"PAUSE":"RESUME"}_${input.moduleName.replace("_WORKER","")}`;if(input.confirmationPhrase!==required)throw new ApiError(400,`Confirmation phrase must be ${required}`,"CONFIRMATION_REQUIRED");
 return transaction(async client=>{await client.query("SELECT pg_advisory_xact_lock(hashtext($1))",[`operations:module:${input.moduleName}`]);const existing=(await client.query("SELECT new_state FROM operations_admin_actions WHERE idempotency_key=$1",[input.idempotencyKey])).rows[0];if(existing)return existing.new_state;const id=await adminId(client,input.adminWallet),before=(await client.query("SELECT * FROM system_module_controls WHERE module_name=$1 FOR UPDATE",[input.moduleName])).rows[0];const after=(await client.query(`UPDATE system_module_controls SET is_paused=$2,pause_reason=CASE WHEN $2 THEN $3 ELSE NULL END,paused_by=CASE WHEN $2 THEN $4 ELSE paused_by END,paused_at=CASE WHEN $2 THEN now() ELSE paused_at END,resumed_by=CASE WHEN $2 THEN NULL ELSE $4 END,resumed_at=CASE WHEN $2 THEN NULL ELSE now() END,updated_at=now(),version=version+1 WHERE module_name=$1 RETURNING *`,[input.moduleName,input.paused,input.reason.trim(),id])).rows[0];await client.query(`INSERT INTO operations_admin_actions(admin_user_id,action_type,module_name,target_type,target_id,reason,confirmation_phrase,previous_state,new_state,request_metadata,idempotency_key) VALUES($1,$2,$3,'MODULE',$3,$4,$5,$6,$7,$8,$9)`,[id,input.paused?"PAUSE_MODULE":"RESUME_MODULE",input.moduleName,input.reason.trim(),input.confirmationPhrase,JSON.stringify(before),JSON.stringify(after),JSON.stringify(input.requestMetadata||{}),input.idempotencyKey]);return after})
}
export const pauseModule=(moduleName:OperationModule,adminWallet:string,reason:string,confirmationPhrase:string,idempotencyKey:string,requestMetadata?:Record<string,unknown>)=>setModuleState({moduleName,paused:true,adminWallet,reason,confirmationPhrase,idempotencyKey,requestMetadata});
export const resumeModule=(moduleName:OperationModule,adminWallet:string,reason:string,confirmationPhrase:string,idempotencyKey:string,requestMetadata?:Record<string,unknown>)=>setModuleState({moduleName,paused:false,adminWallet,reason,confirmationPhrase,idempotencyKey,requestMetadata});
