import{randomUUID}from"node:crypto";import type{PoolClient}from"pg";import{getPool,query,transaction}from"./db";
export function getWithdrawalConfig(){const decimals=Number(process.env.NEXT_PUBLIC_USDT_DECIMALS||6),minimum=BigInt(process.env.AUTO_WITHDRAW_MINIMUM_UNITS||10**decimals),feeBps=BigInt(process.env.AUTO_WITHDRAW_FEE_BPS||1000);return{enabled:(process.env.AUTO_WITHDRAW_ENABLED||"false").toLowerCase()==="true",minimum,feeBps,network:process.env.AUTO_WITHDRAW_NETWORK||"BEP20",interval:Math.max(30,Number(process.env.AUTO_WITHDRAW_WORKER_INTERVAL_SECONDS||60)),maxRetries:Math.max(1,Number(process.env.AUTO_WITHDRAW_MAX_RETRIES||5))}}
export function calculateWithdrawal(gross:bigint,feeBps=1000n){if(gross<=0n)throw new RangeError("Withdrawal must be positive");const fee=gross*feeBps/10_000n;return{gross,fee,net:gross-fee}}
async function available(client:PoolClient,userId:string){const row=(await client.query<{balance:string}>(`SELECT COALESCE(sum(CASE direction WHEN 'CREDIT' THEN amount ELSE -amount END),0)::text balance FROM income_wallet_ledger WHERE user_id=$1`,[userId])).rows[0];return BigInt(row.balance)}
export async function enqueueAutomaticWithdrawal(client:PoolClient,userId:string){const cfg=getWithdrawalConfig();if(!cfg.enabled)return null;await client.query("SELECT pg_advisory_xact_lock(hashtext($1))",[`withdrawal:user:${userId}`]);if((await client.query("SELECT 1 FROM auto_withdrawals WHERE user_id=$1 AND status IN('PENDING','RESERVED','BROADCASTING','BROADCASTED','FAILED_RETRYABLE')",[userId])).rowCount)return null;const balance=await available(client,userId);if(balance<cfg.minimum)return null;const user=(await client.query<{wallet_address:string}>("SELECT wallet_address FROM users WHERE id=$1 AND status='ACTIVE'",[userId])).rows[0];if(!user)return null;const{fee,net}=calculateWithdrawal(balance,cfg.feeBps),key=`auto-withdraw:${userId}:${randomUUID()}`;const withdrawal=(await client.query<{id:string}>(`INSERT INTO auto_withdrawals(user_id,payout_address,gross_reserved,fee_amount,net_payout,status,idempotency_key) VALUES($1,$2,$3,$4,$5,'RESERVED',$6) RETURNING id`,[userId,user.wallet_address,balance.toString(),fee.toString(),net.toString(),key])).rows[0];await client.query(`INSERT INTO income_wallet_ledger(user_id,withdrawal_id,direction,amount,reason,idempotency_key) VALUES($1,$2,'DEBIT',$3,'WITHDRAWAL_RESERVE',$4)`,[userId,withdrawal.id,balance.toString(),`${key}:reserve`]);await client.query(`INSERT INTO auto_withdrawal_audit_logs(withdrawal_id,user_id,event_type,idempotency_key,metadata) VALUES($1,$2,'RESERVED',$3,$4)`,[withdrawal.id,userId,`${key}:audit:reserved`,JSON.stringify({gross:balance.toString(),fee:fee.toString(),net:net.toString()})]);return withdrawal.id}
export async function scanAutomaticWithdrawals(){const users=(await query<{user_id:string}>(`SELECT user_id FROM income_wallet_ledger GROUP BY user_id HAVING sum(CASE direction WHEN 'CREDIT' THEN amount ELSE -amount END)>0`)).rows;let created=0;for(const row of users){const id=await transaction(c=>enqueueAutomaticWithdrawal(c,row.user_id));if(id)created++}return created}
export async function processWithdrawalQueue(){const cfg=getWithdrawalConfig();if(!cfg.enabled)return{status:"DISABLED" as const,processed:0};if((process.env.WITHDRAWAL_BROADCAST_ENABLED||"false").toLowerCase()!=="true")return{status:"BROADCAST_DISABLED" as const,processed:0};return(await import("./withdrawal-broadcast-service")).processUnifiedWithdrawalQueue()}
export async function reverseUnbroadcastWithdrawal(id:string,reason:string){return transaction(async client=>{const row=(await client.query<{user_id:string;gross_reserved:string;idempotency_key:string;tx_hash:string|null}>(`SELECT user_id,gross_reserved::text,idempotency_key,tx_hash FROM auto_withdrawals WHERE id=$1 FOR UPDATE`,[id])).rows[0];if(!row||row.tx_hash)throw new Error("Only an unbroadcast withdrawal can be reversed");await client.query(`UPDATE auto_withdrawals SET status='REVERSED',updated_at=now() WHERE id=$1`,[id]);await client.query(`INSERT INTO income_wallet_ledger(user_id,withdrawal_id,direction,amount,reason,idempotency_key,metadata) VALUES($1,$2,'CREDIT',$3,'WITHDRAWAL_RELEASE',$4,$5)`,[row.user_id,id,row.gross_reserved,`${row.idempotency_key}:release`,JSON.stringify({reason})]);return{id}})}
export async function withWithdrawalWorkerLock<T>(fn:()=>Promise<T>){const client=await getPool().connect();const ok=(await client.query<{ok:boolean}>("SELECT pg_try_advisory_lock(hashtext('auto-withdraw:worker')) ok")).rows[0].ok;if(!ok){client.release();return null}try{return await fn()}finally{await client.query("SELECT pg_advisory_unlock(hashtext('auto-withdraw:worker'))");client.release()}}
export async function getWithdrawalDashboard(userId:string){const[balance,rows]=await Promise.all([query<{balance:string}>(`SELECT COALESCE(sum(CASE direction WHEN 'CREDIT' THEN amount ELSE -amount END),0)::text balance FROM income_wallet_ledger WHERE user_id=$1`,[userId]),query(`SELECT id,payout_address,gross_reserved::text,fee_amount::text,net_payout::text,status,tx_hash,attempt_count,created_at,updated_at FROM auto_withdrawals WHERE user_id=$1 ORDER BY created_at DESC LIMIT 100`,[userId])]);return{availableBalance:balance.rows[0].balance,minimum:getWithdrawalConfig().minimum.toString(),withdrawals:rows.rows}}
