export const SMART_EARNING_ABI = [
  "function register(address sponsor)",
  "function registered(address) view returns (bool)",
  "function registrationPrice() view returns (uint256)",
  "function MAX_LEVELS() view returns(uint8)",
  "function usdt() view returns(address)",
  "function treasuryWallet() view returns(address)",
  "function paymentsPaused() view returns(bool)",
  "function withdrawalsPaused() view returns(bool)",
  "function WITHDRAWAL_EXECUTOR_ROLE() view returns(bytes32)",
  "function AUTHORIZER_ROLE() view returns(bytes32)",
  "function KEEPER_ROLE() view returns(bytes32)",
  "function MAGIC_FUNDING_ROLE() view returns(bytes32)",
  "function PAUSER_ROLE() view returns(bytes32)",
  "function TREASURY_ROLE() view returns(bytes32)",
  "function hasRole(bytes32 role,address account) view returns(bool)",
  "function magicBalance(address) view returns (uint256)",
  "function claimableMagicIncome(address) view returns (uint256)",
  "function directCount(address) view returns (uint256)",
  "function matrixParentOf(address) view returns (address)",
  "function getMatrixChildren(address node) view returns(address left,address right)",
  "function getMatrixChildCount(address node) view returns(uint8)",
  "function getPlacementQueueState(address sponsor) view returns(uint256 head,uint256 size)",
  "function advancePlacementCursor(address sponsor,uint256 maxSteps) returns(bool)",
  "error PlacementSearchNeedsAdvance(address sponsor,uint256 queueHead)",
  "function requiredDirects(uint8) pure returns (uint256)",
  "function currentCycle() view returns (uint256)",
  "function totalEligibleValue(address) view returns (uint256)",
  "function totalPackageValue(address) view returns (uint256)",
  "function totalEarningCap(address) view returns (uint256)",
  "function totalEarned(address) view returns (uint256)",
  "function getRemainingEarningCap(address) view returns (uint256)",
  "function getCappingStatus(address) view returns (uint8)",
  "function distributeBatch(address[] sources,uint256 cycleId)",
  "function fundMagic(address user,uint256 amount,bytes32 sourceReference)",
  "function purchasePackage(uint8 packageId,uint256 amount)",
  "function makePlatformPayment(bytes32 paymentType,uint256 amount,bytes32 sourceReference)",
  "function topupBooster(uint256 amount,bytes32 sourceReference)",
  "function fundWithdrawalLiquidity(uint256 amount,bytes32 sourceReference)",
  "function executeWithdrawal((bytes32 payoutType,bytes32 reservationId,bytes32 earningSource,address user,uint256 chainId,address verifyingContract,uint256 grossAmount,uint256 feeAmount,uint256 netAmount,address destination,uint256 issuedAt,uint256 nonce,uint256 deadline) authorization,bytes signature)",
  "function withdrawalAuthorizationHash((bytes32 payoutType,bytes32 reservationId,bytes32 earningSource,address user,uint256 chainId,address verifyingContract,uint256 grossAmount,uint256 feeAmount,uint256 netAmount,address destination,uint256 issuedAt,uint256 nonce,uint256 deadline) authorization) view returns(bytes32)",
  "function processedWithdrawals(bytes32) view returns(bool)",
  "function processedMagicFunding(bytes32) view returns(bool)",
  "event UserRegistered(address indexed user,address indexed sponsor,address indexed matrixParent,uint256 matrixIndex,uint8 matrixPosition,uint256 directSponsorIncome,uint256 magicWalletCredit)",
  "event MagicDistributed(uint256 indexed cycleId,address indexed source,uint256 distributed,uint256 qualifiedAmount,uint256 pendingAmount)",
  "event MagicLevelAllocated(uint256 indexed cycleId,address indexed source,address indexed beneficiary,uint8 level,uint256 amount,bool qualified)",
  "event EarningCapIncreased(address indexed user,uint256 previousCap,uint256 increaseAmount,uint256 newCap)",
  "event IncomeCapped(address indexed user,bytes32 indexed incomeType,uint256 calculatedAmount,uint256 creditedAmount,uint256 cappedExcessAmount)",
  "event MagicFunded(address indexed user,bytes32 indexed sourceReference,uint256 amount)",
  "event EarningSplit(address indexed user,bytes32 indexed incomeType,uint256 gross,uint256 magicAmount,uint256 incomeAmount)",
  "event PaymentReceived(address indexed user,bytes32 indexed paymentType,uint256 grossAmount,uint256 treasuryAmount,bytes32 sourceReference,uint256 timestamp)",
  "event TreasuryFunded(address indexed user,bytes32 indexed paymentType,uint256 grossAmount,uint256 treasuryAmount,bytes32 sourceReference,uint256 timestamp)",
  "event RegistrationCompleted(address indexed user,uint256 grossAmount,uint256 treasuryAmount,bytes32 indexed sourceReference,uint256 timestamp)",
  "event MagicFundingRecorded(address indexed user,bytes32 indexed paymentType,uint256 grossAmount,uint256 accountingAmount,bytes32 sourceReference,uint256 timestamp)",
  "event MagicIncomeClaimed(address indexed beneficiary,uint256 amount)",
  "event BoosterTopup(address indexed user,uint256 amount,bytes32 indexed sourceReference)",
  "event WithdrawalLiquidityFunded(bytes32 indexed sourceReference,address indexed treasury,uint256 amount,uint256 contractBalance)",
  "event WithdrawalPaid(bytes32 indexed reservationHash,bytes32 indexed reservationId,address indexed user,address destination,bytes32 payoutType,bytes32 earningSource,uint256 grossReservedAmount,uint256 feeAmount,uint256 netAmount,uint256 nonce,address executor,address authorizer)",
  "event TreasuryWalletUpdated(address indexed previousTreasury,address indexed newTreasury,address indexed changedBy)",
  "event PaymentPauseChanged(bool paused)",
  "event WithdrawalPauseChanged(bool paused)",
  "event PlacementCursorAdvanced(address indexed sponsor,uint256 previousHead,uint256 newHead,bool availablePositionFound)",
  "event X4Placed(address indexed user,address indexed owner,uint8 indexed packageId,uint8 slot,uint8 level,uint256 accountingAmount,uint256 cycle)",
  "event X4Recycled(address indexed owner,uint8 indexed packageId,uint256 completedCycle,uint256 newCycle)",
  "event RoleGranted(bytes32 indexed role,address indexed account,address indexed sender)",
  "event RoleRevoked(bytes32 indexed role,address indexed account,address indexed sender)",
  "event RoleAdminChanged(bytes32 indexed role,bytes32 indexed previousAdminRole,bytes32 indexed newAdminRole)",
  "event Paused(address account)",
  "event Unpaused(address account)",
] as const;

export const PACKAGE_ABI = [
  "function registered(address) view returns (bool)",
  "function purchasePackage(uint8 packageId,uint256 amount)",
  "function getPackagePrice(uint8 packageId) view returns (uint256)",
  "function getNextPackage(address user) view returns (uint8)",
  "function hasPurchasedPackage(address user,uint8 packageId) view returns (bool)",
  "function getPurchasedPackages(address user) view returns (bool[8])",
  "function getTotalPackageValue(address user) view returns (uint256)",
  "function getTotalEligibleValue(address user) view returns (uint256)",
  "function getTotalEarningCap(address user) view returns (uint256)",
  "function getTotalEarned(address user) view returns (uint256)",
  "function getRemainingEarningCap(address user) view returns (uint256)",
  "function getCappingStatus(address user) view returns (uint8)",
  "event PackagePurchased(address indexed user,uint8 indexed packageId,uint256 amount,uint256 totalPackageValue,uint256 newEarningCap,uint256 timestamp)",
  "event X3DirectSlotFilled(address indexed buyer,address indexed owner,uint8 indexed packageId,uint256 cycleNumber,uint8 slotNumber,address recipient,uint8 disposition,uint256 packageAmount,uint256 grossAmount)",
  "event X3DirectCycleCompleted(address indexed owner,uint8 indexed packageId,uint256 completedCycle,uint256 nextCycle)",
  "event X4Placed(address indexed user,address indexed owner,uint8 indexed packageId,uint8 slot,uint8 level,uint256 accountingAmount,uint256 cycle)",
  "event X4Recycled(address indexed owner,uint8 indexed packageId,uint256 completedCycle,uint256 newCycle)",
  "event MagicFundingRecorded(address indexed user,bytes32 indexed paymentType,uint256 grossAmount,uint256 accountingAmount,bytes32 sourceReference,uint256 timestamp)",
  "event EarningSplit(address indexed user,bytes32 indexed incomeType,uint256 gross,uint256 magicAmount,uint256 incomeAmount)",
] as const;

export const ERC20_ABI = [
  "function transfer(address to,uint256 amount) returns (bool)",
  "function approve(address spender,uint256 amount) returns (bool)",
  "function allowance(address owner,address spender) view returns (uint256)",
  "function decimals() view returns (uint8)",
  "function balanceOf(address) view returns (uint256)",
] as const;
