"use client";import{useCallback,useEffect,useState}from"react";import{RefreshCw}from"lucide-react";import{formatTokenUnits}from"@/lib/client/money";import{MatrixHistoryMenu}from"@/components/matrix-history-menu";
type Level={level:number;capacity:number;filled:number;income:string};type Position={position:number;level:number;levelPosition:number;parentPosition:number|null;childSlot:number;wallet:string};
type Entry={id:string;booster_entry_id:string;status:string;filled_positions:number;remaining_positions:number;created_at:string;completed_at:string|null;levels:Level[];positions:Position[]};
type Data={active_entries:number;completed_entries:number;total_entries:number;filled_positions:number;remaining_positions:number;total_income:string;entries:Entry[];history:{id:string;entry_id:string;matrix_level:number;amount:string;source_wallet:string;created_at:string}[]};
const money=(value:string)=>formatTokenUnits(value);
export function AutopoolPage(){const[data,setData]=useState<Data|null>(null),[error,setError]=useState("");const[entryId,setEntryId]=useState("");
 const load=useCallback(async()=>{try{const response=await fetch("/api/autopool",{cache:"no-store"}),body=await response.json();if(!response.ok)throw new Error(body.error||"Autopool unavailable");setData(body);setEntryId(current=>current||body.entries[0]?.id||"");setError("")}catch(e){setError(e instanceof Error?e.message:"Autopool unavailable")}},[]);useEffect(()=>{void load()},[load]);
 if(!data)return <section className="smart-glass-card rounded-[22px] p-5">{error||"Loading Global Autopool..."}</section>;const selected=data.entries.find(entry=>entry.id===entryId)||data.entries[0];
 return <div className="grid gap-4"><section className="smart-glass-card rounded-[22px] p-5"><p className="dash-label">100% GLOBAL · FIFO</p><h1 className="mt-1 text-2xl font-bold">Global Autopool</h1><div className="mt-4 grid grid-cols-2 gap-2 md:grid-cols-6">{[["Active entries",data.active_entries],["Completed entries",data.completed_entries],["Total entries",data.total_entries],["Filled positions",data.filled_positions],["Remaining",data.remaining_positions],["Total income",money(data.total_income)]].map(([label,value])=><div className="rounded-xl border border-[#00f77a]/10 bg-black/20 p-3" key={String(label)}><small className="text-[#8b9d94]">{label}</small><b className="mt-1 block text-sm text-[#00f77a]">{value}</b></div>)}</div></section>
 {data.entries.length>0&&<section className="smart-glass-card matrix-history-host rounded-[22px] p-5">{selected&&<MatrixHistoryMenu module="AUTOPOOL" entryId={selected.id} title="Global Autopool Matrix"/>}<div className="flex flex-wrap items-center justify-between gap-2 pr-8"><div><p className="dash-label">CURRENT MATRIX</p><h2 className="font-bold">2 → 6 → 18 → 54 → 162</h2></div><select aria-label="Autopool entry" value={selected?.id} onChange={e=>setEntryId(e.target.value)} className="rounded-xl border border-white/10 bg-[#07100c] px-3 py-2 text-xs">{data.entries.map((entry,index)=><option value={entry.id} key={entry.id}>Entry #{data.entries.length-index} · {entry.status}</option>)}</select></div>
 {selected&&<><div className="mt-4 h-2 overflow-hidden rounded-full bg-white/5"><div className="h-full bg-[#00f77a]" style={{width:`${selected.filled_positions/242*100}%`}}/></div><p className="mt-2 text-xs text-[#8b9d94]">{selected.filled_positions} filled · {selected.remaining_positions} remaining · {selected.status}</p><div className="mt-4 grid gap-2 md:grid-cols-5">{selected.levels.map(level=><div className="rounded-xl border border-white/10 p-3" key={level.level}><b>Level {level.level}</b><span className="mt-2 block text-xs text-[#8b9d94]">{level.filled}/{level.capacity} filled</span><strong className="text-sm text-[#00f77a]">{money(level.income)}</strong></div>)}</div><div className="mt-4 max-h-72 overflow-auto rounded-xl border border-white/5"><div className="grid grid-cols-2 gap-2 p-3 sm:grid-cols-4 md:grid-cols-6">{selected.positions.map(position=><div className="min-w-0 rounded-lg bg-[#00f77a]/5 p-2 text-[9px]" key={position.position}><b>#{position.position} · L{position.level}</b><span className="block truncate text-[#8b9d94]">{position.wallet}</span></div>)}</div></div></>}</section>}
 <section className="smart-glass-card rounded-[22px] p-5"><h2 className="font-bold">Entry & income history</h2><div className="mt-3 max-h-80 overflow-auto">{data.history.map(row=><div className="grid grid-cols-[1fr_auto] border-t border-white/5 py-3 text-xs" key={row.id}><span>Level {row.matrix_level} position filled<small className="block text-[#8b9d94]">{row.source_wallet} · {new Date(row.created_at).toLocaleString()}</small></span><b className="text-[#00f77a]">{money(row.amount)}</b></div>)}{!data.history.length&&<p className="text-xs text-[#8b9d94]">No Autopool income yet.</p>}</div></section><button onClick={load} className="flex items-center gap-2 text-xs text-[#00f77a]"><RefreshCw size={14}/>Refresh Autopool</button></div>}
