"use client";import{useEffect,useState}from"react";const reports=["wallet","topups","entries","queue","positions","income","scheduler","audit"];
export function BoosterAdminPanel(){const[summary,setSummary]=useState<Record<string,string|number>|null>(null),[report,setReport]=useState("wallet"),[items,setItems]=useState<Record<string,unknown>[]>([]),[q,setQ]=useState("");
 async function load(){const[s,r]=await Promise.all([fetch("/api/admin/booster/summary"),fetch(`/api/admin/booster/${report}?q=${encodeURIComponent(q)}`)]);if(s.ok)setSummary(await s.json());if(r.ok)setItems((await r.json()).items||[])}
 async function run(){await fetch("/api/admin/booster/run",{method:"POST"});await load()}
 useEffect(()=>{void load()},[report]);return <section className="smart-glass-card mt-5 rounded-[22px] p-5"><p className="dash-label">BOOSTER</p><h2 className="text-lg font-bold">Booster administration</h2>
 {summary&&<div className="mt-3 grid grid-cols-2 gap-2 md:grid-cols-4">{Object.entries(summary).map(([k,v])=><div className="rounded-xl border border-white/5 p-3" key={k}><small className="text-[#8b9d94]">{k.replaceAll("_"," ")}</small><b className="block text-[#00f77a]">{v}</b></div>)}</div>}
 <div className="mt-4 flex flex-wrap gap-2">{reports.map(x=><button onClick={()=>setReport(x)} className={`rounded-xl border px-3 py-2 text-[10px] ${x===report?"border-[#00f77a]/30 text-[#00f77a]":"border-white/10"}`} key={x}>{x}</button>)}</div>
 <div className="mt-3 flex gap-2"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="User, wallet or transaction hash" className="min-w-0 flex-1 rounded-xl border border-white/10 bg-black/20 px-3 text-xs"/><button onClick={load} className="rounded-xl bg-[#00f77a] px-4 py-3 text-xs font-bold text-black">Search</button><button onClick={run} className="rounded-xl border border-[#00f77a]/30 px-4 py-3 text-xs text-[#00f77a]">Run Booster</button></div>
 <div className="mt-3 max-h-80 overflow-auto text-[10px]">{items.map((x,i)=><pre className="overflow-hidden border-t border-white/5 py-2 text-[#8b9d94]" key={String(x.id||i)}>{JSON.stringify(x)}</pre>)}</div></section>}
