"use client";
import{useCallback,useEffect,useState}from"react";import{Clock,RefreshCw,Wallet}from"lucide-react";import{parseUnits}from"ethers";import{connectTestnet,topUpBoosterWalletOnTestnet}from"@/lib/client/wallet";
import{BoosterCountdown,type BoosterEligibility}from"@/components/booster-countdown";
import{formatTokenUnits}from"@/lib/client/money";
type Entry={id:string;cycle_number:number;status:string;positions:{slotNumber:number;wallet:string}[];created_at:string;completed_at:string|null};
type Data={balance:string;package_credits:string;manual_top_ups:string;refunds:string;deductions:string;nextEntryAt:string|null;
 server_time:string;next_entry_at:string|null;booster_wallet_balance:string;eligibility:BoosterEligibility;status:BoosterEligibility;
 boosterActive:boolean;lastRunAt:string|null;nextEligibleAt:string|null;remainingSeconds:number;
 active_entries:number;completed_entries:number;total_entries:number;pending_positions:number;total_income:string;entries:Entry[];
 walletHistory:{id:string;direction:string;amount:string;reason:string;created_at:string}[];entryHistory:{id:string;type:string;slot_number:number;amount:string;created_at:string}[];
 topUpHistory:{id:string;amount:string;source_reference:string|null;tx_hash:string;status:string;created_at:string}[]};
const money=(v:string)=>formatTokenUnits(v);
export function BoosterPage(){const[data,setData]=useState<Data|null>(null),[error,setError]=useState(""),[amount,setAmount]=useState("2.50"),[busy,setBusy]=useState(false),[status,setStatus]=useState(""),[txHash,setTxHash]=useState("");
 const load=useCallback(async()=>{try{const r=await fetch("/api/booster",{cache:"no-store"}),b=await r.json();if(!r.ok)throw new Error(b.error||"Booster unavailable");setData(b);setError("")}catch(e){setError(e instanceof Error?e.message:"Booster unavailable")}},[]);
 useEffect(()=>{void load()},[load]);async function connect(){setBusy(true);try{const{wallet}=await connectTestnet();setStatus(`Wallet connected: ${wallet}`)}catch(e){setStatus(e instanceof Error?e.message:"Wallet connection failed")}finally{setBusy(false)}}
 async function topUp(){setBusy(true);setTxHash("");try{await topUpBoosterWalletOnTestnet(parseUnits(amount,6),(message,hash)=>{setStatus(message);if(hash)setTxHash(hash)});setStatus("Booster Wallet top-up confirmed");await load()}catch(e){setStatus(e instanceof Error?e.message:"Booster Wallet top-up failed")}finally{setBusy(false)}}
 if(!data)return <section className="smart-glass-card rounded-[22px] p-5">{error||"Loading Booster..."}</section>;
 const cards=[["Booster Wallet balance",money(data.booster_wallet_balance)],["Active entries",data.active_entries],["Completed entries",data.completed_entries],["Total entries",data.total_entries],["Pending positions",data.pending_positions],["Total Booster income",money(data.total_income)],["C-position refunds",money(data.refunds)]];
 return <div className="grid gap-4"><section className="smart-glass-card rounded-[22px] p-5"><p className="dash-label">BOOSTER</p><h1 className="mt-1 text-2xl font-bold">Booster</h1><div className="mt-4 grid grid-cols-2 gap-2 md:grid-cols-4">{cards.map(([a,b])=><div className="rounded-xl border border-[#00f77a]/10 bg-black/20 p-3" key={String(a)}><small className="text-[#8b9d94]">{a}</small><b className="mt-1 block text-sm text-[#00f77a]">{b}</b></div>)}</div></section>
 <section className="smart-glass-card rounded-[22px] border-[#00f77a]/20 p-5"><p className="dash-label">NEXT BOOSTER ENTRY</p>
  <div className="mt-3 grid grid-cols-2 gap-2 text-xs"><span className="rounded-xl border border-[#00f77a]/10 bg-black/20 p-3"><small className="block text-[#8b9d94]">Status</small><b className="mt-1 block">{data.boosterActive?`ACTIVE · ${data.eligibility.replaceAll("_"," ")}`:"INACTIVE"}</b></span><span className="rounded-xl border border-[#00f77a]/10 bg-black/20 p-3"><small className="block text-[#8b9d94]">Last booster run</small><b className="mt-1 block text-[10px]">{data.lastRunAt?new Date(data.lastRunAt).toLocaleString():"Not run"}</b></span><span className="col-span-2 rounded-xl border border-[#00f77a]/10 bg-black/20 p-3"><small className="block text-[#8b9d94]">Next booster time</small><b className="mt-1 block text-[10px]">{data.nextEligibleAt?new Date(data.nextEligibleAt).toLocaleString():"Not scheduled"}</b></span></div>
  <div className="mt-4"><BoosterCountdown serverTime={data.server_time} nextEntryAt={data.next_entry_at} eligibility={data.eligibility} onRefresh={load}/></div></section>
 <section className="smart-glass-card rounded-[22px] p-5"><div className="flex items-center gap-2"><Wallet size={16} className="text-[#00f77a]"/><h2 className="font-bold">Booster Wallet top-up</h2></div><p className="mt-2 text-xs text-[#8b9d94]">Transfer USDT on BNB Smart Chain Testnet from your connected wallet.</p>
 <div className="mt-3 flex flex-wrap gap-2"><input aria-label="Booster Wallet top-up amount" value={amount} onChange={e=>setAmount(e.target.value)} className="min-w-0 flex-1 rounded-xl border border-white/10 bg-black/20 px-3 text-sm"/><button disabled={busy} onClick={connect} className="rounded-xl border border-[#00f77a]/30 px-4 py-3 text-xs font-bold text-[#00f77a] disabled:opacity-50">Connect Wallet</button><button disabled={busy} onClick={topUp} className="rounded-xl bg-[#00f77a] px-4 py-3 text-xs font-bold text-black disabled:opacity-50">Approve USDT &amp; Top up</button></div>{status&&<p className="mt-3 break-words text-xs text-[#8b9d94]">{status}</p>}{txHash&&<p className="mt-1 break-all text-[10px] text-[#8b9d94]">Transaction: {txHash}</p>}</section>
 <div className="grid gap-3 md:grid-cols-2">{data.entries.map(e=><article className="smart-glass-card rounded-[22px] p-5" key={e.id}><div className="flex justify-between"><b>Booster entry #{e.cycle_number}</b><span className="text-[10px] text-[#00f77a]">{e.status}</span></div><div className="mt-4 grid grid-cols-3 gap-2">{[1,2,3].map(s=>{const p=e.positions.find(x=>x.slotNumber===s);return <div className={`min-w-0 rounded-xl border p-3 text-center text-[9px] ${p?"border-[#00f77a]/30 bg-[#00f77a]/5":"border-dashed border-white/10"}`} key={s}><b className="block">{["A","B","C"][s-1]}</b><span className="block truncate text-[#8b9d94]">{p?.wallet||"Empty"}</span></div>})}</div></article>)}</div>
 <History title="Booster Wallet history" rows={data.walletHistory.map(x=>({id:x.id,event:x.reason,amount:`${x.direction==="DEBIT"?"-":"+"}${money(x.amount)}`,date:x.created_at}))}/>
 <History title="Booster top-up history" rows={(data.topUpHistory||[]).map(x=>({id:x.id,event:`${x.status} - ${x.tx_hash}`,amount:`+${money(x.amount)}`,date:x.created_at}))}/>
 <History title="Booster entry history" rows={data.entryHistory.map(x=>({id:x.id,event:`${x.type} ${x.slot_number||""}`,amount:money(x.amount),date:x.created_at}))}/>
 <button onClick={load} className="flex items-center gap-2 text-xs text-[#00f77a]"><RefreshCw size={14}/>Refresh Booster</button></div>}
function History({title,rows}:{title:string;rows:{id:string;event:string;amount:string;date:string}[]}){return <section className="smart-glass-card overflow-hidden rounded-[22px] p-5"><div className="flex items-center gap-2"><Clock size={15}/><h2 className="font-bold">{title}</h2></div><div className="mt-3 max-h-72 overflow-auto">{rows.map(r=><div className="grid grid-cols-[minmax(0,1fr)_auto] gap-2 border-t border-white/5 py-3 text-xs" key={r.id}><span className="min-w-0 break-all">{r.event}<small className="block text-[#8b9d94]">{new Date(r.date).toLocaleString()}</small></span><b className="text-[#00f77a]">{r.amount}</b></div>)}{!rows.length&&<p className="text-xs text-[#8b9d94]">No history yet.</p>}</div></section>}
