'use client';
import Image from'next/image';
import Link from'next/link';
import{usePathname,useRouter}from'next/navigation';
import{ArrowLeft,ChartNoAxesCombined,GitBranch,Home,LogOut,Menu,Sun,Users,Wallet}from'lucide-react';
import{logoutAndRedirect}from'@/lib/client/logout';

const appNav:[string,string,typeof Home][]=[['/dashboard','Home',Home],['/income','Income',ChartNoAxesCombined],['/matrix','Matrix',GitBranch],['/team','Team',Users],['/wallet','Wallet',Wallet]];
function SmartLogo(){return <Link href="/dashboard" className="header-logo-crop" aria-label="Smart Earning dashboard"><Image src="/logo.png" alt="Smart Earning" width={1048} height={356} priority className="header-logo-image object-contain"/></Link>}

export function FixedMetaverseBackground(){return <div className="fixed-metaverse-background" aria-hidden><Image src="/images/smart-earning-metaverse-man.png" alt="" fill priority sizes="100vw" draggable={false}/><div className="fixed-metaverse-overlay"/></div>}
export const SmartEarningBackground=FixedMetaverseBackground;

export function SmartEarningHeader({home=false}:{home?:boolean}){const router=useRouter(),path=usePathname(),matrixHome=path==='/matrix'||path==='/magic-level',showMenu=home||matrixHome;return <header className="dash-header sticky top-0 z-50 flex h-14 items-center justify-between px-3 sm:px-4 lg:ml-60 lg:px-7"><div className="flex min-w-0 items-center gap-1"><button type="button" aria-label={showMenu?"Open menu":"Go back"} onClick={()=>showMenu?router.push('/menu'):history.back()} className="dash-icon">{showMenu?<Menu size={19}/>:<ArrowLeft size={18}/>}</button><SmartLogo/></div><div className="flex items-center gap-1">{home&&<button type="button" aria-label="Light theme" className="dash-icon"><Sun size={17}/></button>}<button type="button" aria-label="Log out" onClick={()=>void logoutAndRedirect()} className="dash-icon"><LogOut size={17}/></button></div></header>}

export function SmartEarningBottomNav(){const path=usePathname();return <nav className="dash-bottom fixed inset-x-3 bottom-[max(10px,env(safe-area-inset-bottom))] z-50 flex h-[86px] items-center justify-around rounded-[28px] px-1.5 lg:hidden">{appNav.map(([href,label,I])=>{const active=path===href||path.startsWith(`${href}/`)||(href==='/matrix'&&path==='/magic-level');return <Link href={href} key={label} className={`flex min-w-[58px] flex-col items-center gap-1.5 rounded-[18px] px-2 py-3 text-[10px] font-semibold transition ${active?'bg-[#00F77A]/14 text-[#F5FFF9] shadow-[inset_0_0_0_1px_rgba(0,247,122,.16)]':'text-[#8B9D94]'}`}><I size={active?21:19} className={active?'text-[#00F77A]':''}/>{label}</Link>})}</nav>}

function SmartEarningSidebar(){const path=usePathname();return <aside className="dash-sidebar fixed inset-y-0 left-0 z-50 hidden w-60 p-5 lg:block"><Link href="/dashboard" aria-label="Smart Earning dashboard"><Image src="/logo.png" alt="Smart Earning" width={1048} height={356} priority className="h-auto w-[132px] object-contain"/></Link><p className="mt-12 px-3 text-[10px] tracking-[.22em] text-[#8B9D94]">NAVIGATION</p><div className="mt-3 space-y-2">{appNav.map(([href,label,I])=>{const active=path===href||path.startsWith(`${href}/`);return <Link key={label} href={href} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-sm ${active?'bg-[#00F77A]/10 text-[#00F77A]':'text-[#8B9D94] hover:text-[#F5FFF9]'}`}><I size={18}/>{label}</Link>})}</div><div className="smart-glass-card absolute bottom-6 left-5 right-5 rounded-2xl p-4 text-xs text-[#8B9D94]">Network<br/><span className="text-[#F5FFF9]">BNB Testnet · Chain 97</span></div></aside>}

export function SmartEarningPageShell({children,home=false}:{children:React.ReactNode;home?:boolean}){return <div className="dashboard-theme smart-internal-shell fixed-background-shell min-h-screen bg-[#020705] text-[#F5FFF9]"><FixedMetaverseBackground/><SmartEarningSidebar/><SmartEarningHeader home={home}/><main className="relative z-[2] mx-auto max-w-[1480px] px-3 pb-[calc(116px+env(safe-area-inset-bottom))] pt-3 sm:px-4 lg:ml-60 lg:px-7 lg:pb-10">{children}</main><SmartEarningBottomNav/></div>}
