"use client";
import Link from"next/link";import{useEffect,useState}from"react";import{AlertTriangle,GitBranch,Lock,RefreshCw,RotateCw}from"lucide-react";
type Slot={slotNumber:number;wallet:string;placementType:string};
type X3Package={packageId:number;priceTokenUnits:string;x3Allocation:string;active:boolean;permanentSponsor:string|null;matrixParent:string|null;currentCycle:number;slots:Slot[];earnedIncome:string;heldIncome:string;releasedIncome:string;recycleCount:number};
const units=(value:string)=>{const n=BigInt(value),whole=n/1_000_000n,fraction=(n%1_000_000n).toString().padStart(6,"0").slice(0,2);return`$${whole}.${fraction}`};
export function X3Page(){const[data,setData]=useState<X3Package[]|null>(null),[error,setError]=useState("");
async function load(){try{const r=await fetch("/api/x3/packages",{cache:"no-store"}),b=await r.json();if(!r.ok)throw new Error(b.error||"X3 data unavailable");setData(b.packages);setError("")}catch(e){setError(e instanceof Error?e.message:"X3 data unavailable")}}
useEffect(()=>{load()},[]);
if(!data)return <section className="smart-glass-card p-5"><AlertTriangle className="text-[#e9ad45]"/><p className="mt-3 text-sm">{error||"Loading package X3 matrices…"}</p><button onClick={load} className="mt-3 flex items-center gap-2 text-xs text-[#00f77a]"><RefreshCw size={14}/>Retry</button></section>;
return <div className="grid gap-4"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{data.map(p=><article className="smart-glass-card rounded-[22px] p-5" key={p.packageId}><div className="flex items-center justify-between"><b>Package {p.packageId} · {units(p.priceTokenUnits)}</b><span className={`rounded-full border px-2 py-1 text-[9px] ${p.active?"border-[#00f77a]/30 text-[#00f77a]":"border-white/10 text-[#8b9d94]"}`}>{p.active?"ACTIVE":"INACTIVE"}</span></div><p className="mt-2 text-xs text-[#8b9d94]">X3 allocation <strong className="text-white">{units(p.x3Allocation)}</strong></p><div className="mt-4 grid grid-cols-3 gap-2">{[1,2,3].map(slot=>{const item=p.slots.find(x=>x.slotNumber===slot);return <span className={`rounded-xl border p-3 text-center text-[9px] ${item?"border-[#00f77a]/30 bg-[#00f77a]/5":"border-dashed border-white/10"}`} key={slot}><b className="block">Slot {slot}</b><small className="mt-1 block truncate text-[#8b9d94]">{item?item.wallet:"Available"}</small><em className="not-italic text-[#00f77a]">{item?.placementType||"—"}</em></span>})}</div><div className="mt-4 grid gap-1 text-[10px] text-[#8b9d94]"><span>Sponsor <b className="float-right max-w-[55%] truncate text-white">{p.permanentSponsor||"Genesis"}</b></span><span>Matrix parent <b className="float-right max-w-[55%] truncate text-white">{p.matrixParent||"Not placed"}</b></span><span>Current cycle <b className="float-right text-white">#{p.currentCycle||0}</b></span><span>Earned <b className="float-right text-[#00f77a]">{units(p.earnedIncome)}</b></span><span>Held <b className="float-right text-[#e9ad45]">{units(p.heldIncome)}</b></span><span>Released <b className="float-right text-white">{units(p.releasedIncome)}</b></span><span>Recycle count <b className="float-right text-white">{p.recycleCount}</b></span></div>{!p.active&&BigInt(p.heldIncome)>0n&&<p className="mt-4 rounded-xl border border-[#e9ad45]/20 bg-[#e9ad45]/5 p-3 text-[10px] text-[#e9ad45]">Activate this package to release your held X3 income.</p>}<Link href="/packages" className="mt-4 flex items-center justify-center gap-2 rounded-xl border border-[#00f77a]/20 bg-[#00f77a]/10 p-3 text-xs text-[#00f77a]">{p.active?<><GitBranch size={14}/>Package matrix active</>:<><Lock size={14}/>Upgrade / Buy Package</>}</Link></article>)}</div><section className="smart-glass-card rounded-[22px] p-5"><div className="flex items-center gap-2"><RotateCw size={16} className="text-[#00f77a]"/><h2 className="font-bold">X3 History</h2></div><p className="mt-2 text-xs text-[#8b9d94]">Placement, held, released, capped and recycle records are package-specific and loaded from verified backend ledgers.</p></section></div>}
